# tasks file for nginx
## Установка nginx для Centos
- name: Install nginx for Centos 
  yum:
    name: nginx
    state: latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - start nginx

## Установка nginx для Debian/Ubuntu
- name: Install nginx Debian/Ubuntu
  apt:
    update_cache: yes
    name: nginx
    state: latest
  when:
    ansible_os_family == "Debian"
  notify:
    - start nginx